/**
 * Analytics Configuration Service API
 * Analytics Configuration Service is responsible for everything related to management of rules, schedules, sensor configurations and models.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsConfigApiV2RuleSpecAttributeMode } from './analyticsConfigApiV2RuleSpecAttributeMode';
import { AnalyticsConfigApiV2RuleSpecAttributeValueUiInfo } from './analyticsConfigApiV2RuleSpecAttributeValueUiInfo';


export interface AnalyticsConfigApiV2RuleSpecAttributeUiInfo { 
    /**
     * Human-readable description of the attribute
     */
    description?: string;
    /**
     * The attribute id
     */
    id?: string;
    /**
     * UI info about the include/exclude modes
     */
    modes?: Array<AnalyticsConfigApiV2RuleSpecAttributeMode>;
    /**
     * Human-readable name of the attribute
     */
    name?: string;
    /**
     * UI info about the available attribute values
     */
    values?: Array<AnalyticsConfigApiV2RuleSpecAttributeValueUiInfo>;
}

