/**
 * Analytics Configuration Service API
 * Analytics Configuration Service is responsible for everything related to management of rules, schedules, sensor configurations and models.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV1RuleDefault } from './githubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV1RuleDefault';
import { AnalyticsConfigApiV2RuleSpecDefaultSensitivity } from './analyticsConfigApiV2RuleSpecDefaultSensitivity';


export interface AnalyticsConfigApiV2RuleSpecRule { 
    /**
     * Available auto sensitivity values for this rule
     */
    autoSensitivity?: Array<string>;
    /**
     * Max distance between people to be considered as group (for Grouping rule)
     */
    clusterDistance?: GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV1RuleDefault;
    /**
     * The object types that are enabled by default. Is nil/omitted if no object types are enabled by default.
     */
    defaultObjectType?: Array<string>;
    /**
     * Dwell Time
     */
    dwellTime?: GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV1RuleDefault;
    /**
     * Time interval [seconds] between statistics reports (for statistics rules)
     */
    intervalTime?: GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV1RuleDefault;
    /**
     * Does this rule require line drawing (true) or area drawing (false)
     */
    isLineDrawing?: boolean;
    /**
     * Min Speed filter (moving in an area, line crossing)
     */
    minSpeed?: GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV1RuleDefault;
    /**
     * Available object types for this rule type
     */
    objectTypes?: Array<string>;
    /**
     * People In Group (for grouping and occupancy rules)
     */
    peopleInGroup?: GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV1RuleDefault;
    /**
     * Is reference crop required
     */
    referenceCrop?: boolean;
    /**
     * Rule group for this rule type
     */
    ruleGroup?: string;
    /**
     * Rule type
     */
    ruleType?: string;
    /**
     * Sensitivity (for Anomaly rule only), defines the expected number of events per day
     */
    sensitivity?: AnalyticsConfigApiV2RuleSpecDefaultSensitivity;
    /**
     * Which object types that would shunt (temporarily deactivate) this rule type. Is nil/omitted if there are no such object types.
     */
    shuntObjectTypes?: Array<string>;
}

