/**
 * Analytics Configuration Service API
 * Analytics Configuration Service is responsible for everything related to management of rules, schedules, sensor configurations and models.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsConfigApiV2RuleSensitivity } from './analyticsConfigApiV2RuleSensitivity';


export interface AnalyticsConfigApiV2RuleSpecDefaultSensitivity { 
    /**
     * Default value
     */
    defaultValue?: AnalyticsConfigApiV2RuleSensitivity;
    /**
     * Max value
     */
    max?: AnalyticsConfigApiV2RuleSensitivity;
    /**
     * Min value
     */
    min?: AnalyticsConfigApiV2RuleSensitivity;
}

