/**
 * Analytics Configuration Service API
 * Analytics Configuration Service is responsible for everything related to management of rules, schedules, sensor configurations and models.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsConfigApiV2GetAccountSettingsResponse } from './analyticsConfigApiV2GetAccountSettingsResponse';


export interface AnalyticsConfigApiV2FindAccountSettingsResponse { 
    /**
     * The Account Settings data
     */
    accountSettings?: Array<AnalyticsConfigApiV2GetAccountSettingsResponse>;
    /**
     * Cursor is an opaque string representing this batch of results. The value can be put in the \'after\' field of another request to fetch the next batch of results. Will be omitted in case there are no more results.
     */
    cursor?: string;
}

