/**
 * Analytics Configuration Service API
 * Analytics Configuration Service is responsible for everything related to management of rules, schedules, sensor configurations and models.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AnalyticsConfigApiV2CreateSensorRequest } from '../model/models';
import { AnalyticsConfigApiV2CreateSensorResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SensorsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Creates a new sensor.
     * 
     * @param request 
     */
    v2SensorsPost(request: AnalyticsConfigApiV2CreateSensorRequest, extraHttpRequestParams?: any): Observable<AnalyticsConfigApiV2CreateSensorResponse>;

}
