/**
 * Analytics Configuration Service API
 * Analytics Configuration Service is responsible for everything related to management of rules, schedules, sensor configurations and models.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2UpdateAccountSettingsResponse { 
    /**
     * Account Id
     */
    accountId?: string;
    /**
     * Flag to indicate that anomaly rule is enabled by default
     */
    enableAnomalyByDefault?: boolean;
    /**
     * Max clip length in secs, 0 means max length of 8 seconds
     */
    eventClipLengthSec?: number;
    /**
     * Limit the number of channels per account (0 means no limit)
     */
    maxChannels?: number;
}

