/**
 * Analytics Configuration Service API
 * Analytics Configuration Service is responsible for everything related to management of rules, schedules, sensor configurations and models.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecAttribute } from './githubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecAttribute';
import { GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecRule } from './githubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecRule';
import { GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecUiInfo } from './githubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecUiInfo';


export interface GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2GetRuleSpecResponse { 
    attributes?: Array<GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecAttribute>;
    rules?: Array<GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecRule>;
    uiInfo?: GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecUiInfo;
}

