/**
 * Analytics Configuration Service API
 * Analytics Configuration Service is responsible for everything related to management of rules, schedules, sensor configurations and models.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2RuleSpecAttributeValueUiInfo { 
    /**
     * Human-readable description of the attribute value
     */
    description?: string;
    /**
     * Icon specification of the attribute value
     */
    icon?: string;
    /**
     * Id of the value
     */
    id?: string;
    /**
     * Human-readable name of the attribute value
     */
    name?: string;
}

