/**
 * Analytics Configuration Service API
 * Analytics Configuration Service is responsible for everything related to management of rules, schedules, sensor configurations and models.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2GetRuleSpecResponse } from '../model/githubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2GetRuleSpecResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {
    RulesServiceInterface
} from './rules.serviceInterface';



@Injectable()
export class RulesService implements RulesServiceInterface {

    protected basePath = 'http://localhost:8088';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string|string[], @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (Array.isArray(basePath) && basePath.length > 0) {
                basePath = basePath[0];
            }

            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    // @ts-ignore
    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, (value as Date).toISOString().substring(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * Get the available rules for this Account (and, optionally, the specified Sensor).
     * @param sensorId Optionally limit the response to what is available for the Sensor with the specified ID.
     * @param language Optionally specify which language to use for returned human-readable texts. Only applicable when \&#39;responseFields\&#39; param contains \&#39;ui\&#39;
     * @param responseFields Comma-separated list of fields to include in response. By default, no fields will be populated.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2RulesSpecGet(sensorId?: string, language?: 'en-US' | 'es-ES' | 'fr-FR' | 'ja-JP' | 'de-DE' | 'ru-RU' | 'hi-IN' | 'zh-CN', responseFields?: Array<'rules' | 'attributes' | 'ui'>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2GetRuleSpecResponse>;
    public v2RulesSpecGet(sensorId?: string, language?: 'en-US' | 'es-ES' | 'fr-FR' | 'ja-JP' | 'de-DE' | 'ru-RU' | 'hi-IN' | 'zh-CN', responseFields?: Array<'rules' | 'attributes' | 'ui'>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2GetRuleSpecResponse>>;
    public v2RulesSpecGet(sensorId?: string, language?: 'en-US' | 'es-ES' | 'fr-FR' | 'ja-JP' | 'de-DE' | 'ru-RU' | 'hi-IN' | 'zh-CN', responseFields?: Array<'rules' | 'attributes' | 'ui'>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2GetRuleSpecResponse>>;
    public v2RulesSpecGet(sensorId?: string, language?: 'en-US' | 'es-ES' | 'fr-FR' | 'ja-JP' | 'de-DE' | 'ru-RU' | 'hi-IN' | 'zh-CN', responseFields?: Array<'rules' | 'attributes' | 'ui'>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (sensorId !== undefined && sensorId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sensorId, 'sensorId');
        }
        if (language !== undefined && language !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>language, 'language');
        }
        if (responseFields) {
            localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                [...responseFields].join(COLLECTION_FORMATS['csv']), 'responseFields');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                '*/*'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v2/rules/spec`;
        return this.httpClient.request<GithubComAgentviInnoviCoreBackendAnalyticsConfigApiApiV2GetRuleSpecResponse>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
